export const NAVIGATION = {
  SCREEN: {
    MAIN: 'NAVIGATION.SCREEN.MAIN',
    TAB: 'NAVIGATION.SCREEN.TAB',
    LOGIN: 'NAVIGATION.SCREEN.LOGIN',
    HOME: 'NAVIGATION.SCREEN.HOME',
    STUDIO: 'NAVIGATION.SCREEN.STUDIO',
    VIDEOPLAYER: 'NAVIGATION.SCREEN.VIDEOPLAYER',
    LIBRARY: 'NAVIGATION.SCREEN.LIBRARY',
    SAVED: 'NAVIGATION.SCREEN.SAVED',
    NOTIFICATIONS: 'NAVIGATION.SCREEN.NOTIFICATIONS',
    STORYBOOK: 'NAVIGATION.SCREEN.STORYBOOK',
    BOOKMARKED: 'NAVIGATION.SCREEN.BOOKMARKED',
    RECORDING: 'NAVIGATION.SCREEN.RECORDING',
    PROFILE: 'NAVIGATION.SCREEN.PROFILE',
    GROUPS: 'NAVIGATION.SCREEN.GROUPS',
    EVENTS: 'NAVIGATION.SCREEN.EVENTS',
    CONVERSATIONS: 'NAVIGATION.SCREEN.CONVERSATIONS',
    NEWPOST: 'NAVIGATION.SCREEN.NEWPOST',
    PROFILEDETAIL: 'NAVIGATION.SCREEN.PROFILEDETAL',
    POSTVIEW: 'NAVIGATION.SCREEN.POSTVIEW',
    BOOKMARKS: 'NAVIGATION.SCREEN.BOOKMARKS',
    TAGSPEOPLE: 'NAVIGATION.SCREEN.TAGSPEOPLE',
    COMMUNITYDETAIL: 'NAVIGATION.SCREEN.COMMUNITYDETAIL'
  }
}
