export const NAVIGATION = {
  SCREEN: {
    MAIN: 'NAVIGATION.SCREEN.MAIN',
    LOGIN: 'NAVIGATION.SCREEN.LOGIN',
    HOME: 'NAVIGATION.SCREEN.HOME',
    STUDIO: 'NAVIGATION.SCREEN.STUDIO',
    VIDEOPLAYER: 'NAVIGATION.SCREEN.VIDEOPLAYER',
    LIBRARY: 'NAVIGATION.SCREEN.LIBRARY',
    SAVED: 'NAVIGATION.SCREEN.SAVED',
    SETTINGS: 'NAVIGATION.SCREEN.SETTINGS',
    STORYBOOK: 'NAVIGATION.SCREEN.STORYBOOK',
    BOOKMARKED: 'NAVIGATION.SCREEN.BOOKMARKED'
  }
}
