fastlane_require 'dotenv'

default_platform(:ios)

platform :ios do

  desc "Submit a new Release Build"
  lane :distribute_release do |options|
    VERSION = options[:version]
    NOTES = options[:notes]
    FIREBASE_TOKEN = options[:firebase_token]
    LIFE_CYCLE = options[:life_cycle]
    TESTERS = options[:testers]
    GROUPS = options[:groups]
    PROD_RELEASE = LIFE_CYCLE === 'prod'
    APP_ID_FIREBASE = {
      'dev' => "1:237851896241:ios:7fc1af02b48a5920cb7590",
    }

    ios_set_version(
      version: VERSION,
      xcodeproj: "connectmobile.xcodeproj"
    )

    ios_set_build_number(
      xcodeproj: "connectmobile.xcodeproj"
    )

    update_code_signing_settings(
      path: "connectmobile.xcodeproj",
      use_automatic_signing: true
    )

    clear_derived_data

    build_app(
      scheme: "connectmobile",
      workspace: "connectmobile.xcworkspace",
      clean: true,
      export_method: "#{PROD_RELEASE ? 'app-store' : 'ad-hoc'}",
      export_options: {
        provisioningProfiles: { 
          "com.connectmobile" => "#{PROD_RELEASE ? 'App Store distribution (CNT)' : 'App Hoc distribution (CNT)'}"
        }
      },
      xcargs: "-allowProvisioningUpdates"
    )

    if (!PROD_RELEASE)
      firebase_app_distribution(
        app: APP_ID_FIREBASE[LIFE_CYCLE],
        testers: TESTERS,
        groups: GROUPS,
        release_notes: NOTES,
        firebase_cli_token: FIREBASE_TOKEN
      )
    else
      app_store_connect_api_key(
        key_id: "?",
        issuer_id: "?",
        key_filepath: "./fastlane/AuthKey_???.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
      )

      # Automatically loads Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
      # pilot

      # sync_code_signing(type: "appstore")

      upload_to_testflight(
        email: "e_morales-itaik@kw.com"
      )
      # upload_to_app_store
    end
  end
end
