export default {
  GET_TODAY_EVENTS: 'GET_TODAY_EVENTS',
  GET_TODAY_EVENTS_SUCCESS: 'GET_TODAY_EVENTS_SUCCESS',
  GET_TODAY_EVENTS_FAILURE: 'GET_TODAY_EVENTS_FAILURE',
  GET_TOMORROW_EVENTS: 'GET_TOMORROW_EVENTS',
  GET_TOMORROW_EVENTS_SUCCESS: 'GET_TOMORROW_EVENTS_SUCCESS',
  GET_TOMORROW_EVENTS_FAILURE: 'GET_TOMORROW_EVENTS_FAILURE'
}
