export default {
  GET_PICK_PROMPTS: 'GET_PICK_PROMPTS',
  GET_PICK_PROMPTS_SUCCESS: 'GET_PICK_PROMPTS_SUCCESS',
  GET_PICK_PROMPTS_FAILURE: 'GET_PICK_PROMPTS_FAILURE',
  GET_POSTS: 'GET_POSTS',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE: 'GET_POSTS_FAILURE'
}
