export default {
  LOG_IN: 'LOG_IN',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_OUT: 'LOG_OUT',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  SET_LOGGED_SUCCESS: 'SET_LOGGED_SUCCESS',
  SET_SESSION_USER: 'SET_SESSION_USER',
  SET_SESSION_USER_SUCCESS: 'SET_SESSION_USER_SUCCESS',
  SET_SESSION_USER_FAILURE: 'SET_SESSION_USER_FAILURE'
}
