export default {
  GET_USRPROFILE: 'GET_USRPROFILE',
  GET_USRPROFILE_SUCCESS: 'GET_USRPROFILE_SUCCESS',
  GET_USRPROFILE_FAILURE: 'GET_USRPROFILE_FAILURE',
  GET_ACCOUNTS: 'GET_ACCOUNTS',
  GET_ACCOUNTS_SUCCESS: 'GET_ACCOUNTS_SUCCESS',
  GET_ACCOUNTS_FAILURE: 'GET_ACCOUNTS_FAILURE',
  CHANGE_ACTIVE_ACCOUNT_SUCCESS: 'CHANGE_ACTIVE_ACCOUNT_SUCCESS'
}
