export default {
  GET_VIDEOS: 'GET_VIDEOS',
  GET_VIDEOS_SUCCESS: 'GET_VIDEOS_SUCCESS',
  GET_VIDEOS_FAILURE: 'GET_VIDEOS_FAILURE',
  REFRESH_VIDEOS: 'REFRESH_VIDEOS',
  REFRESH_VIDEOS_SUCCESS: 'REFRESH_VIDEOS_SUCCESS',
  REFRESH_VIDEOS_FAILURE: 'REFRESH_VIDEOS'
}
