export default {
  GET_BOOKMARKED_VIDEOS: 'GET_BOOKMARKED_VIDEOS',
  GET_BOOKMARKED_VIDEOS_SUCCESS: 'GET_BOOKMARKED_VIDEOS_SUCCESS',
  GET_BOOKMARKED_VIDEOS_FAILURE: 'GET_BOOKMARKED_VIDEOS_FAILURE',
  REFRESH_BOOKMARKED_VIDEOS: 'REFRESH_BOOKMARKED_VIDEOS',
  REFRESH_BOOKMARKED_VIDEOS_SUCCESS: 'REFRESH_BOOKMARKED_VIDEOS_SUCCESS',
  REFRESH_BOOKMARKED_VIDEOS_FAILURE: 'REFRESH_BOOKMARKED_VIDEOS_FAILURE'
}
