export default {
  GET_VIDEOS: 'GET_VIDEOS',
  GET_VIDEOS_SUCCESS: 'GET_VIDEOS_SUCCESS',
  GET_VIDEOS_FAILURE: 'GET_VIDEOS_FAILURE',
  REFRESH_VIDEOS: 'REFRESH_VIDEOS',
  REFRESH_VIDEOS_SUCCESS: 'REFRESH_VIDEOS_SUCCESS',
  REFRESH_VIDEOS_FAILURE: 'REFRESH_VIDEOS',
  LIKE_VIDEO: 'LIKE_VIDEO',
  LIKE_VIDEO_SUCCESS: 'LIKE_VIDEO_SUCCESS',
  LIKE_VIDEO_FAILURE: 'LIKE_VIDEO_FAILURE',
  DISLIKE_VIDEO: 'DISLIKE_VIDEO',
  DISLIKE_VIDEO_SUCCESS: 'DISLIKE_VIDEO_SUCCESS',
  DISLIKE_VIDEO_FAILURE: 'DISLIKE_VIDEO_FAILURE',
  BOOKMARK_VIDEO: 'BOOKMARKED_VIDEO',
  BOOKMARK_VIDEO_SUCCESS: 'BOOKMARKED_VIDEO_SUCCESS',
  BOOKMARK_VIDEO_FAILURE: 'BOOKMARKED_VIDEO_FAILURE'
}
