export default {
  GET_VIDEOS_BM: 'GET_VIDEOS_BM',
  GET_VIDEOS_BM_SUCCESS: 'GET_VIDEOS_BM_SUCCESS',
  GET_VIDEOS_BM_FAILURE: 'GET_VIDEOS_BM_FAILURE',
  REFRESH_BM_VIDEOS: 'REFRESH_BM_VIDEOS',
  REFRESH_VIDEOS_BM_SUCCESS: 'REFRESH_VIDEOS_BM_SUCCESS',
  REFRESH_VIDEOS_BM_FAILURE: 'REFRESH_VIDEOS_BM_FAILURE'
}
